[project]
name = "flashvlm"
version = "0.1.0"
readme = "README.md"
license = { text = "MIT" }
description = "FlashVLM - llava package for multimodal evaluation"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["llava*"]
